export const CREATE_ASSIGNMENT_REQUEST = 'CREATE_ASSIGNMENT_REQUEST';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL';

export const UPDATE_ASSIGNMENT_REQUEST = 'UPDATE_ASSIGNMENT_REQUEST';
export const UPDATE_ASSIGNMENT_SUCCESS = 'UPDATE_ASSIGNMENT_SUCCESS';
export const UPDATE_ASSIGNMENT_FAIL = 'UPDATE_ASSIGNMENT_FAIL';

export const GET_ASSIGNMENT_REQUEST = 'GET_ASSIGNMENT_REQUEST';
export const GET_ASSIGNMENT_SUCCESS = 'GET_ASSIGNMENT_SUCCESS';
export const GET_ASSIGNMENT_FAIL = 'GET_ASSIGNMENT_FAIL';

export const FIND_ASSIGNMENT_REQUEST = 'FIND_ASSIGNMENT_REQUEST';
export const FIND_ASSIGNMENT_SUCCESS = 'FIND_ASSIGNMENT_SUCCESS';
export const FIND_ASSIGNMENT_FAIL = 'FIND_ASSIGNMENT_FAIL';

export const DELETE_ASSIGNMENT_REQUEST = 'DELETE_ASSIGNMENT_REQUEST';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_FAIL = 'DELETE_ASSIGNMENT_FAIL';

export const STORE_ASSIGNMENT = 'STORE_ASSIGNMENT';
export const REMOVE_STORE_ASSIGNMENT = 'REMOVE_STORE_ASSIGNMENT';
export const FIND_OWN_ASSIGNMENT_REQUEST = 'FIND_OWN_ASSIGNMENT_REQUEST';
export const FIND_OWN_ASSIGNMENT_SUCCESS = 'FIND_OWN_ASSIGNMENT_SUCCESS';
export const FIND_OWN_ASSIGNMENT_FAIL = 'FIND_OWN_ASSIGNMENT_FAIL';

export const CHANGE_STATUS_ASSIGNMENT_REQUEST = 'CHANGE_STATUS_ASSIGNMENT_REQUEST';
export const CHANGE_STATUS_ASSIGNMENT_SUCCESS = 'CHANGE_STATUS_ASSIGNMENT_SUCCESS';
export const CHANGE_STATUS_ASSIGNMENT_FAIL = 'CHANGE_STATUS_ASSIGNMENT_FAIL';

export const CREATE_REQUEST_FOR_RETURNING_ASSET_REQUEST =
  'CREATE_REQUEST_FOR_RETURNING_ASSET_REQUEST';
export const CREATE_REQUEST_FOR_RETURNING_ASSET_SUCCESS =
  'CREATE_REQUEST_FOR_RETURNING_ASSET_SUCCESS';
export const CREATE_REQUEST_FOR_RETURNING_ASSET_FAIL = 'CREATE_REQUEST_FOR_RETURNING_ASSET_FAIL';

export const COMPLETE_RETURNING_REQUEST_REQUEST = 'COMPLETE_RETURNING_REQUEST_REQUEST';
export const COMPLETE_RETURNING_REQUEST_SUCCESS = 'COMPLETE_RETURNING_REQUEST_SUCCESS';
export const COMPLETE_RETURNING_REQUEST_FAIL = 'COMPLETE_RETURNING_REQUEST_FAIL';

export const CANCEL_RETURNING_REQUEST_REQUEST = 'CANCEL_RETURNING_REQUEST_REQUEST';
export const CANCEL_RETURNING_REQUEST_SUCCESS = 'CANCEL_RETURNING_REQUEST_SUCCESS';
export const CANCEL_RETURNING_REQUEST_FAIL = 'CANCEL_RETURNING_REQUEST_FAIL';
