export const stateList = [
  {
    name: 'All',
  },
  {
    name: 'Assigned',
  },
  {
    name: 'Available',
  },
  {
    name: 'Not Available',
  },
  {
    name: 'Waiting for recycling',
  },
  {
    name: 'Recycled',
  },
];

export const CREATE_ASSET_REQUEST = 'ASSETS_CREATE_REQUEST';
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS';
export const CREATE_ASSET_FAIL = 'CREATE_ASSET_FAIL';

export const UPDATE_ASSET_REQUEST = 'UPDATE_ASSET_REQUEST';
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS';
export const UPDATE_ASSET_FAIL = 'UPDATE_ASSET_FAIL';

export const DELETE_ASSET_REQUEST = 'DELETE_ASSET_REQUEST';
export const DELETE_ASSET_SUCCESS = 'DELETE_ASSET_SUCCESS';
export const DELETE_ASSET_FAIL = 'DELETE_ASSET_FAIL';

export const GET_ASSET_REQUEST = 'GET_ASSET_REQUEST';
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS';
export const GET_ASSET_FAIL = 'GET_ASSET_FAIL';

export const GET_ASSET_FOR_EDIT_ASSIGNMENT_REQUEST = 'GET_ASSET_FOR_EDIT_ASSIGNMENT_REQUEST';
export const GET_ASSET_FOR_EDIT_ASSIGNMENT_SUCCESS = 'GET_ASSET_FOR_EDIT_ASSIGNMENT_SUCCESS';
export const GET_ASSET_FOR_EDIT_ASSIGNMENT_FAIL = 'GET_ASSET_FOR_EDIT_ASSIGNMENT_FAIL';

export const FIND_ASSETS_REQUEST = 'FIND_ASSETS_REQUEST';
export const FIND_ASSETS_SUCCESS = 'FIND_ASSETS_SUCCESS';
export const FIND_ASSETS_FAIL = 'FIND_ASSETS_FAIL';

export const GET_ASSETS_ASSIGNMENT_HISTORY_REQUEST = 'GET_ASSETS_ASSIGNMENT_HISTORY_REQUEST';
export const GET_ASSETS_ASSIGNMENT_HISTORY_SUCCESS = 'GET_ASSETS_ASSIGNMENT_HISTORY_SUCCESS';
export const GET_ASSETS_ASSIGNMENT_HISTORY_FAIL = 'GET_ASSETS_ASSIGNMENT_HISTORY_FAIL';

export const STORE_ASSET = 'STORE_ASSET';
export const REMOVE_STORE_ASSET = 'REMOVE_STORE_ASSET';

export const CLEAR_DELETE_ASSET_ERROR = 'CLEAR_DELETE_ASSET_ERROR';
