export const CREATE_CATEGORY_REQUEST = 'CATEGORY_CREATE_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CATEGORY_ASSET_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CATEGORY_ASSET_FAIL';

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
export const GET_ALL_CATEGORIES_FAIL = 'GET_ALL_CATEGORIES_FAIL';
