export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USERS_LOGIN_FAIL = 'USERS_LOGIN_FAIL';

export const USERS_LOGOUT = 'USERS_LOGOUT';

export const USERS_GET_CURRENT_USER_DATA = 'USERS_GET_CURRENT_USER_DATA';
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const STORE_USER = 'STORE_USER';
export const REMOVE_STORE_USER = 'REMOVE_STORE_USER';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const USERS_CHANGE_PASSWORD_REQUEST = 'USERS_CHANGE_PASSWORD_REQUEST';
export const USERS_CHANGE_PASSWORD_SUCCESS = 'USERS_CHANGE_PASSWORD_SUCCESS';
export const USERS_CHANGE_PASSWORD_FAIL = 'USERS_CHANGE_PASSWORD_FAIL';

export const USERS_CHECK_ABLE_TO_DISABLE_REQUEST = 'USERS_CHECK_ABLE_TO_DISABLE_REQUEST';
export const USERS_CHECK_ABLE_TO_DISABLE_SUCCESS = 'USERS_CHECK_ABLE_TO_DISABLE_SUCCESS';
export const USERS_CHECK_ABLE_TO_DISABLE_FAIL = 'USERS_CHECK_ABLE_TO_DISABLE_FAIL';

export const DISABLE_USER_REQUEST = 'DISABLE_USER_REQUEST';
export const DISABLE_USER_SUCCESS = 'DISABLE_USER_SUCCESS';
export const DISABLE_USER_FAIL = 'DISABLE_USER_FAIL';
